routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::delete('/requisition','RequisitionController@clear')->name('requisition.clear');

Route::group(['middleware' =>'auth'], function()
	{
		Route::resources([
			'items' => 'ItemController',
			'units' => 'UnitController',
			'unit_statuses' =>'unitStatusController',
			'requisition' => 'RequisitionController',
			'tickets' => 'TicketController'
		]);
});

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Item extends Model
{
	use SoftDeletes;
	
    protected $fillable = ["name"];

    public function units(){

    	return $this->hasMany('App\Unit');
   	}
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use App\Unit;
use App\Status;
use App\unitStatus;
use Illuminate\Http\Request;
use DB;
use Str;
use Brian2694\Toastr\Facades\Toastr;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $items = Item::all()->sortBy('name');

        // store total units and available units per item
        foreach($items as $item){
            $item->total = DB::table('units')
                ->where('item_id',$item->id)
                ->whereNull('deleted_at')
                ->count();

            $item->available = DB::table('units')
                ->where('item_id',$item->id)
                ->where('unit_status_id',1)
                ->whereNull('deleted_at')
                ->count();
            $item->save();
        }
        
        return view('items.index')->with('items',$items);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // authenticate 
        $this-> authorize('create',Item::class);

        return view('items.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        // authenticate 
        $this-> authorize('create',Item::class);

        // validate passed data
        $validatedData = $request->validate([
            'name' => 'required|unique:items,name',
        ]);

        $item = new Item($validatedData);

        $item->save();

        Toastr::success('Genre added successfully');
        return redirect( route('items.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {

       $ctrl_code = strtoupper(Str::random(6));
       $item_code = strtoupper(Str::substr($item->name,0,3));
        return view('items.show')
            ->with('item',$item)
            ->with('unit_statuses',unitStatus::all())
            ->with('units',Unit::all()->where('item_id',$item->id))
            ->with('ctrl_code',$ctrl_code)
            ->with('item_code',$item_code);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {   
        // authenticate 
        $this-> authorize('create',Item::class);

        return view('items.edit')->with('item',$item);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        // authenticate 
        $this-> authorize('update',Item::class);

        $validatedData = $request->validate([
            'name' => 'required|unique:items,name'
        ]);

        $item->update($validatedData);

        $item->save();

        Toastr::success('Genre edited successfully');
        return redirect( route('items.show', $item->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {   
        // authenticate 
        $this-> authorize('delete',Item::class);

        $item->delete();

        Toastr::warning('Genre deleted successfully');
        return redirect( route('items.index'));
    }
}

resources/views/items/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<div class="my-3">
				<a href="{{ route('items.show',$item->id)}}">View Item</a>
			</div>
			<h3> Edit <strong>{{ $item->name }}</strong></h3>
			<div class="my-3">
				<form action="{{ route('items.update',$item->id) }}" method="post">
					@csrf
					@method('PUT')
					<div class="input-group">
						<input type="text" class="form-control" id="name" name="name" value="{{ $item->name }}">
						
							<script>
								@if(count($errors) > 0)
									@foreach($errors->all() as $error)
										toastr.error("{{ $error }}");
									@endforeach
								@endif
							</script>
			
						<div class="input-group-append">
							<button type="submit" class="btn btn-outline-success">Edit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/items/index.blade.php
@extends('layouts.app')

@section('title', '| Genres')
@section('content')
	<div class="container mt-5">
		<div class="row justify-content-center">
			<div class="col-12 ">
					<div class="container" id="allitems">
						@foreach($items as $item)
							@include('items.partials.card')
						@endforeach
					</div>
					@can('isAdmin')
					<div class="container" id="createitem">
						@include('items.partials.create-item')
					</div>
					@endcan
					<script>
						@if(count($errors) > 0)
							@foreach($errors->all() as $error)
									toastr.error("{{ $error }}");
							@endforeach
						@endif
						
					</script>
			</div>
			{{-- end right content --}}
		</div>
	</div>
@endsection

resources/views/items/show.blade.php
@extends('layouts.app')

@section('content')

	<div class="container my-5">
	<div class="row">
		<div class="col-12">
			<div class="card bg-dark text-white mb-5">
				<img class="card-img" src="https://images.pexels.com/photos/210764/pexels-photo-210764.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="Card image">
				<div class="card-img-overlay" id="cardimg">
					<h2 class="card-title"><strong>{{$item->name}}</strong></h2>
					<p class="card-text">Current Available: {{ $item->available}}/{{ $item->total}}</p>
					    {{--hide if normal user --}}
					    @can('isAdmin')
					     	<a href = "{{ route( 'items.edit', $item->id ) }}" class="btn btn-lg btn-dark">
						      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
						        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
						      </svg>
					    	</a>
					     	<form action="{{ route('items.destroy',$item->id)}}" method="post" class="d-inline-block">
					        @csrf
					        @method('DELETE')
					        <button class="btn btn-lg btn-danger">
					        	<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					          		<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
					          		<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
					        	</svg>
					    	</button>
					      	</form>
					    @endcan
				</div>
			</div>
		</div>
	</div>
			
		<div class="row">
			{{-- start of item/unit left side --}}
			<div class="col-12 col-md-4 col-lg-3 mx-auto">
				{{-- hide if normal user --}}

				{{-- hide if normal user --}}
				@can('isAdmin')
					{{-- start of create unit container --}}
					<div class="my-2 add-record">
						<h5 class="text-center">Add Record</h5>

						<form action="{{ route('units.store')}}" method="post" enctype="multipart/form-data" >
							@csrf
							
							{{-- name --}}
							<div class="form-group">
								<label for="name">Record Name</label>
								<input type="text" name="name" id="name" class="form-control">
							</div>

							{{-- control-code --}}
							<div class="form-group">
								<label for="control_code">Record Code</label>
								<div class="input-group">
									<div class="input-group-prepend">
										<span class="input-group-text">{{$item_code}} -
									</div>
									<input type="text" name="control_code" id="control_code" class="form-control" value="{{$ctrl_code}}">

								</div>
							</div>

							{{-- image --}}
							<div class="form-group">
								<label for="image">Image</label>
								<input type="file" name="image" id="image" class="form-control-file">
							</div>
							
							{{-- item --}}
							<div class="form-group">
								<label for="item_id">Genre</label>
								<select name="item_id" id="item_id" class="form-control">
										<option value="{{ $item->id}}">{{ $item->name}}</option>
								</select>
							</div>

							{{-- unit_status --}}
							<div class="form-group">
								<label for="unit_status_id">Record Status</label>
								<select name="unit_status_id" id="unit_status_id" class="form-control">
									@foreach($unit_statuses as $unit_status)
										<option value="{{ $unit_status->id}}">{{ $unit_status->name}}</option>
									@endforeach
								</select>
								
							</div>
							
							<button class="btn btn-secondary w-100" type="submit">Submit</button>

						</form>
					</div>
					{{-- end create unit container --}}
				@endcan
			</div>
			{{-- end of item/unit left side --}}
			
			{{-- start of show units right side --}}
			<div class="col-12 col-md-8 col-lg-9">
				<div class="row">
					<div class="products-wrapper mt-3">
					<div class="row row-small-gutter">
						@foreach($units as $unit)
							{{-- {{ dd($unit->name)}} --}}
							 @include('units.partials.card')
						@endforeach
					</div>
				</div>
				</div>
				
			</div>
			{{-- end of show units right side --}}
		</div>
		<script>
			@if(count($errors) > 0)
				@foreach($errors->all() as $error)
					toastr.error("{{ $error }}");
				@endforeach
			@endif
		</script>
	</div>


@endsection